FROM ubuntu:16.10

RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y openssh-client iproute2 iputils-ping net-tools && \
    apt-get clean

CMD ["/bin/bash"]
